Data:
  data_root: /data/rlsam2/datasets/jpg/MSD/Task06_Lung
  train_list: ./lists/coco/train.txt
  val_list: ./lists/coco/val.txt
  classes: 2

Train:
  # Aug
  train_h: 1024
  train_w: 1024
  val_size: 1024
  scale_min: 1.0  # minimum random scale
  scale_max: 1.0 # maximum random scale
  rotate_min: 0  # minimum random rotate
  rotate_max: 0  # maximum random rotate
  ignore_label: 255
  padding_label: 255
  # Dataset & Mode
  split: 0
  shot: 5
  data_set: 'msd_task06'
  use_split_coco: False # True means FWB setting
  # Optimizer
  batch_size: 4 # batch size for training (bs8 for 1GPU)
  base_lr: 0.0001
  epochs: 50
  start_epoch: 0
  stop_interval: 25 # stop when the best result is not updated for "stop_interval" epochs
  index_split: -1 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0
  warmup: False
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume: # path to latest checkpoint (default: none, such as epoch_10.pth)  
  # Validate
  evaluate: True
  SubEpoch_val: False # val at the half epoch
  fix_random_seed_val: True
  batch_size_val: 1
  resized_val: True
  ori_resize: False  # use original label for evaluation
  # Else
  workers: 8
  fix_bn: True
  manual_seed: 321
  seed_deterministic: False
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  
Method:
  layers: 50  # Resnet in PSPNet
  vgg: False
  sam2_type: 'tiny'
  sam2_weight: '/data/rlsam2/checkpoints/sam2_hiera_tiny.pt'
  sam2_config: 'sam2_hiera_t.yaml'
  aux_weight1: 0.0
  aux_weight2: 0.0

Test_Finetune:
  weight: best_5shot.pth # load weight for fine-tuning or testing (such as train5_epoch_47.5_0.4926.pth)
  ann_type: 'mask' # mask/bbox
